### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bjoliveau**
Add roadmap

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks :+1:

**Comment by dreispt** [comment]
Wouldn't it be nicer to use checkboxes instead of bullets?

**Comment by bjoliveau** [comment]
Hi Daniel, 
Nice idea.
Have we a template roadmap for OCA repo anywhere ?

**Comment by houssine78** [comment]
:+1:

**Comment by houssine78** [comment]
Hi @bjoliveau 

we are planning to develop exportation of answer to xls in the way of google forms do it. If there is some interest to have it in this repo, you could add it to the roadmap and I will make a pull request as soon as we finish it.

**Comment by yvaucher** [comment]
:+1:

**Comment by Ehtaga** [comment]
:+1:

**Pull request merged**
