### PR TITLE
[15.0][FIX] survey_resource_booking: adapt to partner refactor

### PR DESCRIPTION
**Pull request by chienandalu**
We need to adapt tests to https://github.com/OCA/calendar/pull/110

cc @Tecnativa TT45338

please review @carolinafernandez-tecnativa @pedrobaeza

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Fast-tracking this as obvious:

/ocabot merge patch

**Comment by chienandalu** [comment]
Also failing affecting to the tests in sale_resource_booking and website_sale_resource_booking (investigating...)

**Comment by pedrobaeza** [comment]
One way to avoid this compatibility problem is to add an inverse function to `partner_id` field, so that it put on `partner_ids` the proper value. Do you know what I mean?

**Comment by chienandalu** [comment]
Yes, I was thinking about that, although in this case the problem is that using the `Form` class, the field should be in the view

**Comment by pedrobaeza** [comment]
Not sure if putting it as invisible will serve.

**Pull request merged**
