### PR TITLE
[MIG] survey_legal: Migration to 15.0

### PR DESCRIPTION
**Pull request by chienandalu**
Aside from migration adaptations:

- Drop website_require_legal dependency
- Validation is now performed in js insead of the view so we need to do so.
- Additional control for the legal terms link and text

cc @Tecnativa TT44775

please review @victoralmau @pilarvargas-tecnativa

### CODE REVIEW

**Review by victoralmau — APPROVED** [review]
Code and functional review OK

**Review by rafaelbn — APPROVED** [review]
👍🏼 

Tested in runbot 

imagen

**Comment by chienandalu** [comment]
Thanks @rafaelbn :wink: anyway, the merge command wasn't `patch`, but `nobump` as the version is already raised in the migration process

**Comment by rafaelbn** [comment]
I know, there are two ways 😄 . @rousseldenis and me use `patch` always. Reasons are somewhere in a detailed explanation in a PR.

**Comment by pedrobaeza** [comment]
But that "reason" was for older versions (13-). On recent versions, no version bumping is needed, as @rousseldenis can confirm.

**Pull request merged**
