### PR TITLE
[14.0][ADD] survey_question_type_binary

### PR DESCRIPTION
**Pull request by zamberjo**
New module that enables the option to upload files in the surveys, controlling both the type of file uploaded and its size.
It also adds the possibility of adding several files with the option "Multiple: Binary".

### CODE REVIEW

**Comment by zamberjo** [comment]
Pre-commit is fixed with https://github.com/OCA/survey/pull/90.

**Review by belenaures — APPROVED** [review]
Checked to see if I could upload correctly more than 1 image in a binary question, works ok

**Review by chienandalu — APPROVED** [review]
Tested :+1:

**Pull request merged**
