### PR TITLE
[15.0][FIX] survey_crm_generation: support all answers for lead description

### PR DESCRIPTION
**Pull request by chienandalu**
Make use of survey_result_mail answers builder to get rich format answers of all the supported types.

TT40979  cc @Tecnativa TT40979

please review @pedrobaeza @pilarvargas-tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
And what about #88 ?

**Comment by chienandalu** [comment]
> And what about #88 ?

Yes, that would be the idea. To pull that dependency so we can use a common method, but I should refactor it a little bit

**Comment by pedrobaeza** [comment]
OK, go ahead with it.

**Comment by chienandalu** [comment]
Please re-review @pilarvargas-tecnativa @pedrobaeza

**Review by pilarvargas-tecnativa — APPROVED** [review]
Tested locally, thanks :)

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
