### PR TITLE
[10.0][MIG] partner_survey

### PR DESCRIPTION
**Pull request by grindtildeath**

### CODE REVIEW

**Review by damdam-s — APPROVED** [review]
:+1: technical review

**Comment by chienandalu** [comment]
Hi, @grindtildeath I PR'd to your migration just to adjust authors new company.

**Comment by rafaelbn** [comment]
Hi @grindtildeath , tested in runbor 👍 . Please could you check and fix travis red? Thanks! 😄

**Review by rafaelbn — CHANGES_REQUESTED** [review]
tested in runbot 👍 just fix travis to get merged

**Comment by grindtildeath** [comment]
@rafaelbn Thanks for testing. Had to change a bit the copyrights from @chienandalu, but I suppose it's ok.

**Review by rafaelbn — APPROVED** [review]

**Pull request merged**
