### PR TITLE
[15.0][MIG] survey_crm_sale_generation: Migration to version 15.0

### PR DESCRIPTION
**Pull request by stefan-tecnativa**
cc @Tecnativa TT43780

@chienandalu @victoralmau please review!

### CODE REVIEW

**Comment by victoralmau** [comment]
Could you rebase to remove `test-requirements.txt` changes?

**Comment by chienandalu** [comment]
> Could you rebase to remove `test-requirements.txt` changes?

ping @stefan-tecnativa 

please review @pilarvargas-tecnativa

**Comment by stefan-tecnativa** [comment]
> > Could you rebase to remove `test-requirements.txt` changes?
> 
> ping @stefan-tecnativa
> 
> please review @pilarvargas-tecnativa

I rebased the commit but forgot to remove the test-requirements file. Fixed, thanks.

**Review by victoralmau — APPROVED** [review]
Code review OK

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
