### PR TITLE
[16.0][MIG] survey_question_type_nps: Migration to 16.0

### PR DESCRIPTION
**Pull request by janikvonrotz**
Standard migration from 14.0 to 16.0.

### CODE REVIEW

**Comment by alessandro-fiorino** [comment]
Is there any reason why it is still not merged ?

**Comment by rousseldenis** [comment]
> Is there any reason why it is still not merged ?

@alessandro-fiorino Because that depends on contribution. And contribution is based on contributors goodwill. It seems nobody attracted by this.

You can for sure review it as contribution.

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by alessandro-fiorino — APPROVED** [review]
Code reviewed, made some tests.

**Review by chienandalu — APPROVED** [review]
Tested locally :+1:

**Pull request merged**
