### PR TITLE
[15.0][IMP] partner_survey recovered form view

### PR DESCRIPTION
**Pull request by arielbarreiros96**
Recovered form view on action, removed previously during migration to 13 https://github.com/OCA/survey/pull/33
This feature cloud also be restored on https://github.com/OCA/survey/pull/87 since the PR is not yet merged

### CODE REVIEW

**Review by christian-ramos-tecnativa — APPROVED** [review]
LGTM

**Review by rrebollo — APPROVED** [review]
Code Review LGTM

**Comment by antoniodavid** [comment]
LGTM

**Review by antoniodavid — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge minor

**Pull request merged**
