### PR TITLE
[16.0][MIG] survey_question_type_binary: Migration to 16.0

### PR DESCRIPTION
**Pull request by jguenat**
Migration from 14.0 and a fix
If fix accepted I'll backport it to 14.0

### CODE REVIEW

**Comment by jguenat** [comment]
HI @zamberjo 
Do you have time to review this migration / fix ?
Let me know if you need help elsewhere in OCA
Thanks

**Review by zamberjo — APPROVED** [review]
LGTM

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
